#############################################################
# Filename: ~/.zshrc
#############################################################

# Init cool-dotfiles versioned zsh runtime
[ -s "$HOME/.config/zsh/init.zsh" ] && source "$HOME/.config/zsh/init.zsh"

#+++++++++++++++++++++++++++++++++++++++
# USER-DEFINED Afterwards
#+++++++++++++++++++++++++++++++++++++++
