name: Build and Push DevContainer Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (for multi-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check devcontainer changes
        uses: dorny/paths-filter@v3
        id: devcontainer-changes
        with:
          filters: |
            devcontainer:
              - 'setups/devcontainer/Dockerfile'

      # Build and push Docker image
      - name: Build and push devcontainer image
        if: steps.devcontainer-changes.outputs.matched
        uses: docker/build-push-action@v5
        with:
          context: .
          file: setups/devcontainer/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devcontainer:latest
